FROM node:18.12.1 AS build
#FROM node:18 AS build
WORKDIR /app
COPY ./web/package*.json ./
RUN npm install
COPY ./web/public public/
COPY ./web/src src/
ENV REACT_APP_SERVER=https://luckynow.cn:8080
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build/ /usr/share/nginx/html
COPY ./web/config/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]