version: "3"

services:
  monitor_springboot:
#    image: monitor:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile_SpringBoot
    container_name: monitor
    ports:
      - "8080:8080"
    networks:
      - monitor_net
    depends_on:
      - monitor_redis
      - monitor_mysql
    command:
      - --spring.datasource.url=jdbc:mysql://monitor_mysql:3306/monitoring?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      - --spring.datasource.username=root
      # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
      - --spring.datasource.password=123456
      # 外部访问地址，请根据实际需要修改
#      - --halo.external-url=http://localhost:8080/
      # 发生消息的邮箱，验证码的邮箱
      - --spring.mail.username=xuzhe
      # 发生消息的邮箱，验证码的密码
      - --spring.mail.password=D


  monitor_mysql:
    image: mysql:8.0.31
    container_name: monitor_mysql
    ports:
      - "3307:3306"
    volumes:
      # 数据挂载
      - /root/mysql/data/:/var/lib/mysql/
      # 配置挂载
      - /root/mysql/conf/:/etc/mysql/conf.d/
      # 初始化目录挂载
      - /root/mysql/init/:/docker-entrypoint-initdb.d/
#      - ./mysqlBackup:/data/mysqlBackup
#      # 数据挂载
#      - ./mysql/data:/var/lib/mysql/
#      # 配置挂载
#      - ./mysql/conf:/etc/mysql/conf.d/
#      - ./mysql/my.cnf:/etc/my.cnf

    networks:
      - monitor_net
    environment:
      # 请修改此密码，并对应修改上方 monitor_springboot 服务的 spring.datasource.password 变量值
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=monitoring


  monitor_react:
    #    image: monitor:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile_React
    container_name: react_monitor
    ports:
      - "80:80"
    networks:
      - monitor_net
    depends_on:
      - monitor_springboot


  monitor_redis:
    image: redis:6.2.6
    container_name: redis_monitor
    ports:
      - "6379:6379"
    volumes:
      - /root/redis/data:/data
      - /root/redis/conf/redis.conf:/etc/redis/redis.conf
    networks:
      - monitor_net
    environment:
        - TZ=Asia/Shanghai
    command: ["redis-server","/etc/redis/redis.conf"]

networks:
  monitor_net: