version: "3"

services:
  monitor_springboot:
#    image: monitor:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile_SpringBoot
    container_name: monitor
    ports:
      - "8080:8080"
    networks:
      - monitor_net
    depends_on:
#      - redis
      - mysql_monitor
    command:
      - --spring.datasource.url=jdbc:mysql://mysql_monitor:3306/monitoring?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      - --spring.datasource.username=root
      # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
      - --spring.datasource.password=123456
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=http://localhost:8080/
      - --spring.mail.username=xuzhen5678@163.com
      - --spring.mail.username=DJDPSAQQYMXOFNLW


  mysql_monitor:
    image: mysql:8.0.31
    container_name: mysql_monitor
    ports:
      - "3307:3306"
    volumes:
      # 数据挂载
      - /root/mysql/data/:/var/lib/mysql/
      # 配置挂载
      - /root/mysql/conf/:/etc/mysql/conf.d/
      # 初始化目录挂载
      - /root/mysql/init/:/docker-entrypoint-initdb.d/
#      - ./mysqlBackup:/data/mysqlBackup
#      # 数据挂载
#      - ./mysql/data:/var/lib/mysql/
#      # 配置挂载
#      - ./mysql/conf:/etc/mysql/conf.d/
#      - ./mysql/my.cnf:/etc/my.cnf

    networks:
      - monitor_net
    environment:
      # 请修改此密码，并对应修改上方 Halo 服务的 SPRING_R2DBC_PASSWORD 变量值
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=monitoring


  monitor_react:
    #    image: monitor:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile_React
    container_name: react_monitor
    ports:
      - "80:80"
    networks:
      - monitor_net
    depends_on:
      - monitor_springboot

networks:
  monitor_net: